<?php
if ($this->group)
{
	$this->placeholder('top')->set('<h3>'.$this->group->title.'</h3>'.$this->group->description);
	Z_Seo::addTitle($this->group->title);
}
else
{
	$this->placeholder('top')->set('<h1>Новости</h1>');
	Z_Seo::addTitle('Новости');
}
Z_Seo::addTitle($this->item->title);
?>

            <div class="news">
            
                <div class="item">
                    <h1><?php echo $this->item->title?></h1>
                    <span class="date"><?php echo date('d-m-Y',strtotime($this->item->date))?></span>
                    <hr />
                    <div class="info">
                    	<?php if ($this->item->pic):?>
                    	<img src="<?php echo $this->z_Preview($this->item->pic,array('w'=>200))?>" alt="" class="logo" />
                    	<?php endif;?>
                        <?php echo $this->item->text?>
                        <a href="<?php echo $this->url(array('action'=>'index','group'=>$this->item->group_id),'newsgroup')?>">Вернуться в список.</a>
                    </div>
                    <div class="clear"></div>
                </div>

            </div>