<?php if ($this->pageCount>1): ?>
	<div class="paginate">
	
		<a title="На первую страницу" href="<?php echo $this->url(array('page' => $this->first==1?null:$this->first)); ?>" >&laquo;</a>
		
		<a title="На предыдущую страницу" href="<?php echo $this->url(array('page' => $this->previous==1?NULL:$this->previous)); ?>" >&lsaquo;</a>
		
		<?php foreach ($this->pagesInRange as $page): ?>
		
		    <a href="<?php echo $this->url(array('page' => $page==1?NULL:$page)); ?>" <?php echo $page == $this->current?'class="active"':'' ?>><?php echo $page; ?></a>
		    
		<?php endforeach; ?>
		
		<a title="На следующую страницу" href="<?php echo $this->url(array('page' => $this->next==1?NULL:$this->next)); ?>" >&rsaquo;</a>
		
		<a title="На последнюю страницу" href="<?php echo $this->url(array('page' => $this->last)); ?>" >&raquo;</a>
		
	</div>
<?php endif; ?>
