<?php
	$this->placeholder('top')->set('<h3>'.$this->band->title.'</h3>'.$this->band->description);
	Z_Seo::addTitle($this->band->title);
    Z_Seo::addTitle($this->item->title);
?>

            <div class="news">

                <div class="item">
                    <h1><?php echo $this->item->title?></h1>
                    <span class="date"><?php echo date('d-m-Y',strtotime($this->item->date))?></span>
                    <hr />
                    <div class="info">
                    	<?php if ($this->item->file):?>
                    	<img src="<?php echo $this->z_Preview($this->item->file,array('w'=>200))?>" alt="" class="logo" />
                    	<?php endif;?>
                        <?php echo $this->item->text?>
                        <a href="<?php echo $this->list_url?>">Вернуться в список.</a>
                    </div>
                    <div class="clear"></div>
                </div>

            </div>