<?php
    $this->placeholder('top')->set('<h1>'.$this->band->title.'</h1>'.$this->band->description);
	Z_Seo::addTitle($this->band->title);
?>

            <div class="news">

<?php foreach ($this->items as $item):?>

                <div class="item">

                	<?php if ($item->text):?>
                    <h3><a href="<?php echo $item->card_url?>"><?php echo $item->title?></a></h3>
                    <?php else:?>
                    <h3><?php echo $item->title?></h3>
                    <?php endif;?>

                    <span class="date"><?php echo date('d-m-Y',strtotime($item->date))?></span>
                    <hr />
                    <div class="info">
                    	<?php if ($item->file):?>
                    	<img src="<?php echo $this->z_Preview($item->file,array('w'=>120))?>" alt="" class="logo" />
                    	<?php endif;?>
                        <?php echo $item->description?>

	                	<?php if ($item->text):?>
                        <a href="<?php echo $item->card_url?>">Читать далее...</a>
	                    <?php endif;?>

                    </div>
                    <div class="clear"></div>
                </div>

<?php endforeach;?>

            </div>

<?php echo $this->paginationControl($this->items,'Sliding','paginator.phtml')?>
